env_type: realworld

total_num_envs: null

auto_reset: true
ignore_terminations: true
reward_mode: raw
wrap_obs_mode: simple
seed: 0
group_size: 1
use_fixed_reset_state_ids: false
max_steps_per_rollout_epoch: 4
max_episode_steps: 4
use_spacemouse: false
main_image_key: head_color
state_order:
  - left_joint_position
  - left_gripper
  - right_joint_position
  - right_gripper

operator_control:
  mode: automatic
  timeout_s: 0.0

video_cfg:
  save_video: false
  info_on_video: true
  video_base_dir: ${runner.logger.log_path}/video/train

init_params:
  id: F1DualArmPegInsertionEnv-v1
  num_envs: null
